### ISSUE TITLE
Difference between this and flake-parts?

### ISSUE THREAD

**Issue by collinarnett** [jonringer/flake-v2#1]
As someone who is not familiar with the internals of flakes, how is this different from flake-parts? Not trying to be antagonistic, just coming from a place of genuine curiosity :slightly_smiling_face: . I think the flake-parts interface is great and should be the default implementation but maybe there are technical limitations based on the current flake schema that I am unaware of.

**Comment by jonringer** [comment]
I think there's a lot of alignment between this and https://github.com/hercules-ci/flake-parts. This is more of a "if there was a clean slate on how flakes would be structured, this is how I would like it to be structured".

I think the main difference is that I'm really fixated on overlays being the first class citizen of package composition. However, there's nothing from my "design" which forces you to use them either.

**Comment by nrdxp** [comment]
Also, it may be important to mention that flake-parts uses the module system, which is highly complex and therefore prone to long and obnoxious traces, whereas building a new schema into flakes directly avoids that additional complexity, which I feel is highly appropriate for a core feature.

**Comment by jonringer** [comment]
Succinctly, my desire here is: "Create a coherent package set, expose packages from that package set, as well as expose non-package related things like nixosModules, overlays, etc".

I'm not trying to revolutionize how repo's can leverage nix, rather just make it easier to expose such things.

module system are immensely powerful, but they come at the cost of complexity. And I think that complexity is warranted in a lot of other locations, but this isn't one of them :)
